# https://dart.dev/tools/pub/automated-publishing#hardening-security-with-tag-protection-rules-on-github
name: Publish to pub.dev

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+' # tag pattern on pub.dev: 'v{{version}'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
      - name: Analyze
        run: dart analyze
      - name: Format
        run: dart format --set-exit-if-changed .
      - name: Dry run
        run: flutter pub publish --dry-run
  test:
    uses: ./.github/workflows/ci.yml
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: Dry run
        run: flutter pub publish --dry-run
      - name: Publish
        run: dart pub publish